
version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7
    restart: always

  backend:
    build: ./backend-django
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend-django:/app
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend-nextjs
    volumes:
      - ./frontend-nextjs:/app
    env_file: .env
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable
    volumes:
      - ./infrastructure/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
